title: Yoseph Buitrago
description: 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "yosephbuitrago" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Yoseph Buitrago # add your name
author-img: yoseph-buitrago.jpg # add your photo
about-author: I am an electronic engineer with a degree in Information Technology.   Always looking for new challenges and technologies to play with it that help me to improve my career # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: yosephbuitrago # add your Github handle
linkedin: yosephbuitrago
email: yosephbuitrago.01@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
